// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLPractice_Fridge.Models;

namespace SQLPractice_Fridge.Migrations
{
    [DbContext(typeof(FridgeContext))]
    [Migration("20200917172500_initDatabase")]
    partial class initDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SQLPractice_Fridge.Models.Fridge", b =>
                {
                    b.Property<int>("shelfID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("itemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shelfCapacity")
                        .HasColumnType("int");

                    b.HasKey("shelfID");

                    b.ToTable("Fridge");
                });

            modelBuilder.Entity("SQLPractice_Fridge.Models.FridgeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FridgeshelfID")
                        .HasColumnType("int");

                    b.Property<int>("itemCount")
                        .HasColumnType("int");

                    b.Property<string>("itemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FridgeshelfID");

                    b.ToTable("FridgeItem");
                });

            modelBuilder.Entity("SQLPractice_Fridge.Models.FridgeItem", b =>
                {
                    b.HasOne("SQLPractice_Fridge.Models.Fridge", null)
                        .WithMany("shelfInventory")
                        .HasForeignKey("FridgeshelfID");
                });
#pragma warning restore 612, 618
        }
    }
}
