// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLPractice_Fridge.Models;

namespace SQLPractice_Fridge.Migrations
{
    [DbContext(typeof(FridgeContext))]
    [Migration("20200918125131_initDatabase2")]
    partial class initDatabase2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SQLPractice_Fridge.Models.Fridge", b =>
                {
                    b.Property<int>("FridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("shelfCapacity")
                        .HasColumnType("int");

                    b.Property<string>("shelfType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FridgeId");

                    b.ToTable("FridgeShelf");
                });

            modelBuilder.Entity("SQLPractice_Fridge.Models.FridgeItem", b =>
                {
                    b.Property<int>("FridgeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("itemCount")
                        .HasColumnType("int");

                    b.Property<string>("itemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FridgeItemId");

                    b.ToTable("FridgeItem");
                });

            modelBuilder.Entity("SQLPractice_Fridge.Models.FridgeShelf", b =>
                {
                    b.Property<int>("FridgeShelfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FridgeItemId")
                        .HasColumnType("int");

                    b.HasKey("FridgeShelfId");

                    b.ToTable("Shelf");
                });
#pragma warning restore 612, 618
        }
    }
}
